name: "Setup SonarScanner"
description: "Sets up SonarScanner CLI for Linux in your GitHub Actions workflow."

inputs:
  version:
    required: false
    default: "4.7.0.2747"
    description: "SonarScanner CLI version to install"

runs:
  using: "composite"
  steps:
    - name: Install SonarScanner
      shell: bash
      run: |
        npm install vitest
        npm run coverage
        curl -LO https://binaries.sonarsource.com/Distribution/sonar-scanner-cli/sonar-scanner-cli-${{ inputs.version }}-linux.zip
        unzip sonar-scanner-cli-${{ inputs.version }}-linux.zip
        echo ./sonar-scanner-${{ inputs.version }}-linux/bin/sonar-scanner >> $SONAR_SCANNER_EXEC
