name: Deploy
description: "ArgoCD based deploy action. Requires kustomize to run."

inputs:
  environment:
    required: true
    description: "Environment to deploy to, e.g. staging, production."
  version:
    required: true
    description: "Container image tag being deployed, e.g. a commit SHA."
  deploying_repo:
    required: true
    description: "Repository which is running the pipeline to deploy from."
  infra_repo:
    required: true
    description: "Repository for ArgoCD to pick up changes from."
  deploy_key:
    required: true
    description: "Private key, with its public counterpart expected to be attached to `infra_repo` as deploy key."
  app:
    required: true
    description: "ArgoCD application to be deployed."
  argocd_pipeline_password:
    required: true
    description: "Password for the `pipeline` user in ArgoCD (read-only permissions for such user are sufficient)."
  argocd_server:
    required: true
    description: "Host name of the server where ArgoCD runs, e.g. argocd.example.com"

runs:
  using: "composite"
  steps:
    - name: Checkout infra repository
      uses: actions/checkout@v3
      with:
        repository: digitalservicebund/${{ inputs.infra_repo }}
        ssh-key: ${{ inputs.deploy_key }}
    - name: Update image tag for ${{ inputs.environment }}
      shell: sh
      run: |
        cd manifests/overlays/${{ inputs.environment }}
        kustomize edit set image ghcr.io/digitalservicebund/${{ inputs.deploying_repo }}:${{ inputs.version }}
    - name: Commit and push changes for infra repository
      # Third-party action, pin to commit SHA!
      # See https://docs.github.com/en/actions/security-guides/security-hardening-for-github-actions
      uses: EndBug/add-and-commit@050a66787244b10a4874a2a5f682130263edc192 # == v9.0.0
      with:
        add: manifests/overlays/${{ inputs.environment }}/kustomization.yaml
        message: "Bump ${{ inputs.environment }} image to ${{ inputs.version }}\n\n[skip ci]"
        pathspec_error_handling: exitImmediately
        push: true
    - name: Trigger Argo CD sync
      shell: sh
      run: |
        curl -sSL -o argocd https://${ARGOCD_SERVER}/download/argocd-linux-amd64
        chmod +x argocd
        ./argocd login ${ARGOCD_SERVER} --username pipeline --password ${{ inputs.argocd_pipeline_password }} --grpc-web
        ./argocd app wait ${{ inputs.app }} --sync --health --timeout 120 --grpc-web
        ./argocd app get --refresh ${{ inputs.app }} --grpc-web > /dev/null
        ./argocd app wait ${{ inputs.app }} --sync --health --timeout 120 --grpc-web
      env:
        ARGOCD_SERVER: ${{ inputs.argocd_server }}
