name: Deploy

on:
  workflow_call:
    inputs:
      environment:
        required: true
        type: string
      version:
        required: true
        type: string
      deploying_repo:
        required: true
        type: string
      infra_repo:
        required: true
        type: string
      app:
        required: true
        type: string
    secrets:
      deploy_key:
        required: true
      argocd_pipeline_password:
        required: true
      argocd_server:
        required: true
      metrics_deployment_webhook_url:
        required: false
      metrics_webhook_token:
        required: false
      slack_webhook_url:
        required: false

jobs:
  deploy:
    runs-on: ubuntu-latest
    environment: ${{ inputs.environment }}
    steps:
      - name: Checkout infra repository
        uses: actions/checkout@v3
        with:
          repository: digitalservice4germany/${{ inputs.infra_repo }}
          ssh-key: ${{ secrets.deploy_key }}
      - name: Update image tag for ${{ inputs.environment }}
        run: |
          cd manifests/overlays/${{ inputs.environment }}
          kustomize edit set image ghcr.io/digitalservice4germany/${{ inputs.deploying_repo }}:${{ inputs.version }}
      - name: Commit and push changes for infra repository
        # Third-party action, pin to commit SHA!
        # See https://docs.github.com/en/actions/security-guides/security-hardening-for-github-actions
        uses: EndBug/add-and-commit@050a66787244b10a4874a2a5f682130263edc192 # == v9.0.0
        with:
          add: manifests/overlays/${{ inputs.environment }}/kustomization.yaml
          message: "Bump ${{ inputs.environment }} image to ${{ inputs.version }}"
          pathspec_error_handling: exitImmediately
          push: true
      - name: Trigger Argo CD sync
        run: |
          curl -sSL -o argocd https://${ARGOCD_SERVER}/download/argocd-linux-amd64
          chmod +x argocd
          ./argocd login ${ARGOCD_SERVER} --username pipeline --password ${{ secrets.argocd_pipeline_password }} --grpc-web
          ./argocd app get --refresh ${{ inputs.app }} --auth-token $(./argocd account generate-token --account ${{ inputs.app }}-deploy --expires-in 300s --grpc-web) --grpc-web > /dev/null
          ./argocd app wait ${{ inputs.app }} --sync --health --grpc-web
        env:
          ARGOCD_SERVER: ${{ secrets.argocd_server }}
      - name: Report deployment
        if: ${{ env.METRICS_DEPLOYMENT_WEBHOOK_URL }}
        run: |
          curl -X POST -H "Authorization: Token ${{ secrets.metrics_webhook_token }}" -H "Content-Type: application/json" -d '{"project":"${{ inputs.app }}","version_identifier":"${{ github.sha }}","environment":"${{ inputs.environment }}","link":"https://github.com/${{ github.repository }}/actions/runs/${{ github.run_id }}"}' env.METRICS_DEPLOYMENT_WEBHOOK_URL
        env:
          METRICS_DEPLOYMENT_WEBHOOK_URL: ${{ secrets.metrics_deployment_webhook_url }}
      - name: Send status to Slack
        # Third-party action, pin to commit SHA!
        # See https://docs.github.com/en/actions/security-guides/security-hardening-for-github-actions
        uses: lazy-actions/slatify@c4847b8c84e3e8076fd3c42cc00517a10426ed65 # == v3.0.0
        if: ${{ failure() && env.SLACK_WEBHOOK_URL }}
        env:
          SLACK_WEBHOOK_URL: ${{ secrets.slack_webhook_url }}
        with:
          type: ${{ job.status }}
          job_name: "Deploy ${{ inputs.environment }} :point_right:"
          mention: "here"
          mention_if: "failure"
          commit: true
          url: ${{ secrets.slack_webhook_url }}
          token: ${{ secrets.GITHUB_TOKEN }}
